import Head from 'next/head';
import {
  Additional,
  Banner,
  ClientReview,
  Feature,
  Houses,
  News,
  Offer,
  Offers,
  ReadyToSell,
  Steps,
  Subcription,
  Trusted,
} from '../src/components';
import Layout from '../src/components/layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>We Buy Houses Fast For Cash | Quality Homes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout>
        <Banner />
        <Offer />
        <Trusted />
        <Steps />
        <Feature />
        <ClientReview />
        <Offers />
        <Houses />
        <Additional />
        <ReadyToSell />
        <News />
        <Subcription />
      </Layout>
    </>
  );
}
