import Head from 'next/head';
import { BlogDetails, SingleBlogBanner } from '../src/components';
import Layout from '../src/components/layout';

export default function SingleBlog() {
  return (
    <>
      <Head>
        <title>Blog - Quality Homes Reimagined, LLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout>
        <SingleBlogBanner />
        <BlogDetails />
      </Layout>
    </>
  );
}
